const fs = require('fs');

console.log('Building perfect website matching reference exactly...');

// 1. Section 1: Birthday reveal iframe
const sec1 = fs.readFileSync('vercel_sec1.html', 'utf8').trim();

// 2. Section 2: Hero Section
let sec2 = fs.readFileSync('vercel_sec2.html', 'utf8').trim();
// Clean any next.js internal artifacts
sec2 = sec2.replace(/jsx-[a-z0-9]+/g, '');

// 3. Section 3: Made For You
let sec3 = fs.readFileSync('vercel_sec3.html', 'utf8').trim();
sec3 = sec3.replace(/caveat_[a-z0-9_-]+__className/g, 'font-caveat');

// 4. Section 4: Scrapbook
let sec4 = fs.readFileSync('vercel_sec4.html', 'utf8').trim();
// Replace Next image URLs with local static URLs
// Example: srcSet="/_next/image?url=%2Fpages%2Ffront.png&amp;w=640&amp;q=75 640w, ..." src="/_next/image?url=%2Fpages%2Ffront.png&amp;w=3840&amp;q=75"
sec4 = sec4.replace(/srcSet="[^"]*"/g, '');
sec4 = sec4.replace(/src="\/_next\/image\?url=%2F([^&]+)&amp;[^"]*"/g, (match, p1) => {
  return `src="/${decodeURIComponent(p1)}"`;
});
sec4 = sec4.replace(/data-nimg="fill"/g, '');
sec4 = sec4.replace(/decoding="async"/g, '');

console.log('Sec1 len:', sec1.length);
console.log('Sec2 len:', sec2.length);
console.log('Sec3 len:', sec3.length);
console.log('Sec4 len:', sec4.length);

// Build complete index.html
const indexHtml = `<!DOCTYPE html>
<html lang="en" class="h-screen overflow-hidden antialiased">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Create Next App</title>
  <meta name="description" content="Generated by create next app" />

  <!-- Google Fonts matching reference -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,300..800&family=Caveat:wght@400..700&family=JetBrains+Mono:wght@400;500&family=Work+Sans:wght@400;500&family=Archivo+Black&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">

  <!-- Reference Tailwind Compiled CSS (contains all scale, rotate, translate utilities) -->
  <link rel="stylesheet" href="/original_app.css" />

  <!-- Tailwind CSS CDN for dynamic utilities -->
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      darkMode: 'class',
      theme: {
        extend: {
          fontFamily: {
            display: ['"Bricolage Grotesque"', 'sans-serif'],
            body: ['"Work Sans"', 'sans-serif'],
            mono: ['"JetBrains Mono"', 'monospace'],
            caveat: ['"Caveat"', 'cursive'],
          }
        }
      }
    }
  </script>

  <!-- PageFlip Library -->
  <script src="/page-flip.browser.js"></script>
  <script>
    if (!window.St || !window.St.PageFlip) {
      document.write('<script src="https://cdn.jsdelivr.net/npm/page-flip@2.0.7/dist/js/page-flip.browser.js"><\\/script>');
    }
  </script>

  <style>
    .hero-display {
      font-family: 'Bricolage Grotesque', sans-serif;
    }
    .hero-body {
      font-family: 'Work Sans', sans-serif;
    }
    .hero-mono {
      font-family: 'JetBrains Mono', monospace;
    }
    .font-caveat {
      font-family: 'Caveat', cursive;
    }
    .transform-3d {
      transform-style: preserve-3d;
    }
    /* Hide scrollbar */
    ::-webkit-scrollbar {
      width: 0px;
      height: 0px;
      background: transparent;
    }
    .book-page {
      position: relative;
      background-color: #fffbeb;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
      overflow: hidden;
      width: 400px;
      height: 500px;
    }
  </style>
</head>
<body class="h-screen w-full overflow-hidden m-0 p-0">
  <div class="h-full w-full overflow-x-hidden overflow-y-scroll snap-y snap-mandatory bg-zinc-50 dark:bg-black select-none scroll-smooth">

    <!-- ================= SECTION 1: BIRTHDAY REVEAL ================= -->
    ${sec1}

    <!-- ================= SECTION 2: HERO SECTION ================= -->
    ${sec2}

    <!-- ================= SECTION 3: MADE FOR YOU ================= -->
    ${sec3}

    <!-- ================= SECTION 4: SCRAPBOOK FLIPBOOK ================= -->
    ${sec4}

  </div>

  <!-- INTERACTIVITY SCRIPTS FOR SECTIONS 2, 3, AND 4 -->
  <script>
    // ==========================================
    // SECTION 2: CURVED MARQUEE ANIMATION & DRAG
    // ==========================================
    (function initCurvedMarquee() {
      const container = document.querySelector('section:nth-of-type(2) .relative.w-full.h-full');
      if (!container) return;

      const nodes = container.querySelectorAll('.absolute.top-0.left-0');
      if (!nodes || nodes.length === 0) return;

      const totalNodes = nodes.length; // 24 items
      const basePositions = [];
      nodes.forEach((node, i) => {
        // offset-distance percentage is set on style
        const match = node.style.offsetDistance ? parseFloat(node.style.offsetDistance) : (i * (100 / totalNodes));
        basePositions.push(match);
      });

      let currentOffset = 0;
      let isHovered = false;
      let isDragging = false;
      let startX = 0;
      let dragVelocity = 0;

      container.addEventListener('mouseenter', () => isHovered = true);
      container.addEventListener('mouseleave', () => isHovered = false);

      container.addEventListener('pointerdown', (e) => {
        isDragging = true;
        startX = e.clientX;
        dragVelocity = 0;
        container.style.cursor = 'grabbing';
      });

      window.addEventListener('pointermove', (e) => {
        if (!isDragging) return;
        const dx = e.clientX - startX;
        startX = e.clientX;
        const delta = dx * 0.08;
        dragVelocity = delta * 30;
        currentOffset = (currentOffset - delta) % 100;
        if (currentOffset < 0) currentOffset += 100;
        updatePositions();
      });

      window.addEventListener('pointerup', () => {
        if (isDragging) {
          isDragging = false;
          container.style.cursor = 'grab';
        }
      });

      function updatePositions() {
        nodes.forEach((node, i) => {
          const pos = (basePositions[i] + currentOffset) % 100;
          node.style.offsetDistance = \`\${pos < 0 ? pos + 100 : pos}%\`;
          node.style.zIndex = Math.floor(1 + ((pos < 0 ? pos + 100 : pos) / 100) * 10);
        });
      }

      let lastTime = performance.now();
      function animate(now) {
        const dt = (now - lastTime) / 1000;
        lastTime = now;

        if (!isDragging) {
          if (Math.abs(dragVelocity) > 0.01) {
            currentOffset = (currentOffset + dragVelocity * dt) % 100;
            dragVelocity *= 0.98;
          }
          const speed = isHovered ? 5 * 0.05 : 5;
          currentOffset = (currentOffset + speed * dt) % 100;
          if (currentOffset < 0) currentOffset += 100;
          updatePositions();
        }

        requestAnimationFrame(animate);
      }
      requestAnimationFrame(animate);
    })();

    // ==========================================
    // SECTION 3: MADE FOR YOU POLAROIDS DRAG & TILT
    // ==========================================
    (function initMadeForYou() {
      const cards = document.querySelectorAll('section:nth-of-type(3) .transform-3d');
      if (!cards || cards.length === 0) return;

      cards.forEach(card => {
        let isDragging = false;
        let startX = 0, startY = 0;
        let transX = 0, transY = 0;
        const glare = card.querySelector('.mix-blend-overlay');

        card.addEventListener('pointerdown', (e) => {
          isDragging = true;
          startX = e.clientX - transX;
          startY = e.clientY - transY;
          card.setPointerCapture(e.pointerId);
          card.style.zIndex = '50';
        });

        card.addEventListener('pointermove', (e) => {
          const rect = card.getBoundingClientRect();
          const centerX = rect.left + rect.width / 2;
          const centerY = rect.top + rect.height / 2;
          const normX = (e.clientX - centerX) / (rect.width / 2);
          const normY = (e.clientY - centerY) / (rect.height / 2);
          const rotX = -normY * 18;
          const rotY = normX * 18;

          if (isDragging) {
            transX = e.clientX - startX;
            transY = e.clientY - startY;
          }

          card.style.transform = \`translate3d(\${transX}px, \${transY}px, 0px) perspective(1000px) rotateX(\${rotX}deg) rotateY(\${rotY}deg)\`;
          if (glare) {
            glare.style.opacity = Math.min(0.25, (Math.abs(rotX) + Math.abs(rotY)) / 100);
          }
        });

        const resetTilt = (e) => {
          isDragging = false;
          try { card.releasePointerCapture(e.pointerId); } catch (_) {}
          card.style.transform = \`translate3d(\${transX}px, \${transY}px, 0px) perspective(1000px) rotateX(0deg) rotateY(0deg)\`;
          if (glare) glare.style.opacity = '0';
        };

        card.addEventListener('pointerup', resetTilt);
        card.addEventListener('pointerleave', resetTilt);
      });
    })();

    // ==========================================
    // SECTION 4: SCRAPBOOK PAGEFLIP
    // ==========================================
    (function initScrapbook() {
      const bookContainer = document.querySelector('section:nth-of-type(4) .flex.h-screen > div');
      if (!bookContainer) return;

      let attempts = 0;
      function setupFlip() {
        if (!window.St || !window.St.PageFlip) {
          if (attempts++ < 50) {
            setTimeout(setupFlip, 100);
          }
          return;
        }

        try {
          const pageFlip = new St.PageFlip(bookContainer, {
            width: 400,
            height: 500,
            size: "fixed",
            autoSize: false,
            showCover: true,
            drawShadow: true,
            maxShadowOpacity: 0.5,
            usePortrait: false,
            startPage: 0
          });

          pageFlip.loadFromHTML(bookContainer.querySelectorAll('.book-page'));

          // Click on left/right half to turn page
          bookContainer.addEventListener('click', (e) => {
            const rect = bookContainer.getBoundingClientRect();
            const clickX = e.clientX - rect.left;
            if (clickX > rect.width / 2) {
              pageFlip.flipNext();
            } else {
              pageFlip.flipPrev();
            }
          });

          // Keyboard navigation
          window.addEventListener('keydown', (e) => {
            if (e.key === 'ArrowRight') pageFlip.flipNext();
            if (e.key === 'ArrowLeft') pageFlip.flipPrev();
          });
        } catch (err) {
          console.warn('PageFlip init error:', err);
        }
      }

      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', setupFlip);
      } else {
        setupFlip();
      }
    })();
  </script>
</body>
</html>`;

fs.writeFileSync('index.html', indexHtml);
console.log('Saved index.html, total size:', indexHtml.length);
